from pathlib import Path

p=Path('index.html')
s=p.read_text(encoding='utf-8')
a=s.index('const products=[')
b=s.index('const supportCopy=',a)
CAT=r'''const products=[
{id:'obd',name:'OBD Active Exhaust Pro',type:'app',tag:'Android App',img:'assets/obd.webp',desc:'Active exhaust, diagnostics, live vehicle data and driver tools.',details:true},
{id:'drive-recorder',name:'Drive Recorder',type:'app',tag:'Android App',img:'7e9c2f92-e74d-474b-b17d-d4345413b7d7.png',desc:'Full HD driving recorder with GPS and loop recording.',details:true},
{id:'watch-faces',name:'ARVION Watch Faces',type:'watch',tag:'Wear OS',img:'assets/watch-faces.webp',desc:'Premium watch faces for compatible Wear OS smartwatches.',details:true},
{id:'checkers-royal',name:'Checkers Royal Game',type:'game',tag:'Game · Wear OS',img:'1f7b7381-74c7-4af8-a345-961b4afd158d.png',desc:'Royal checkers for Android, also available on Wear OS.',details:true},
{id:'royal-chess',name:'Royal Chess',type:'game',tag:'Game',img:'1.jpeg',desc:'Classic chess with AI in a premium royal presentation.',details:true},
{id:'chicken-drop',name:'Chicken Drop',type:'game',tag:'Game',img:'assets/chicken-drop.webp',desc:'Fast and simple arcade gameplay for Android.',details:true},
{id:'crystal-blocks',name:'Crystal Blocks',type:'game',tag:'Game',img:'assets/crystal-blocks.webp',desc:'A crystal-themed falling-block puzzle game.',details:true},
{id:'kalendarz-zmianowy',name:'Kalendarz Zmianowy',type:'app',tag:'Android App',img:'assets/kalendarz.webp',desc:'Shift calendar with schedules, notes and work information.',details:true},
{id:'live-data',name:'Live Data',type:'app',tag:'Android App',img:'assets/live-data.webp',desc:'Real-time vehicle parameters through compatible OBD/ELM327.',details:true},
{id:'media-player',name:'Media Player',type:'app',tag:'Android App',img:'assets/media.webp',desc:'Local media playback with playlists and visualizers.',details:true},
{id:'music-2-watch',name:'Music 2 Watch',type:'watch',tag:'Phone · Wear OS',img:'assets/music-2-watch.webp',desc:'Music features connecting Android phone and smartwatch.',details:true},
{id:'pixel-critters',name:'Pixel Critters',type:'game',tag:'Game',img:'assets/pixel-critters.webp',desc:'A retro pixel virtual-pet experience for Android.',details:true},
{id:'pixel-critters-3d',name:'Pixel Critters 3D',type:'game',tag:'Game',img:'assets/pixel-critters-3d.webp',desc:'A 3D creature adventure with rooms and mini-games.',details:true},
{id:'snake-classic',name:'Snake Classic',type:'game',tag:'Game',img:'assets/snake.webp',desc:'A modern Android edition of the classic Snake game.',details:true},
{id:'spy-2-watch',name:'Spy 2 Watch',type:'watch',tag:'Phone · Wear OS',img:'BANER STRONA GLOWNA.png',desc:'Phone-camera preview and controls designed for smartwatch use.',details:true},
{id:'video-2-watch',name:'Video 2 Watch',type:'watch',tag:'Phone · Wear OS',img:'assets/video-2-watch.webp',desc:'Transfer and play your own videos on a compatible smartwatch.',details:true}
];
const mkProduct=({title,icon,enSub,plSub,en,pl,gallery,play,noteEn='',notePl=''})=>({title,icon,subtitle:{en:enSub,pl:plSub},gallery,copy:{
en:`<h3>${title}</h3><p>${en}</p><p><strong>No ads. No subscriptions.</strong> One purchase with future ARVION updates included.</p><a class="store-button" href="${play}" target="_blank" rel="noopener">GET IT ON GOOGLE PLAY</a>${noteEn?`<span class="store-note">${noteEn}</span>`:''}`,
pl:`<h3>${title}</h3><p>${pl}</p><p><strong>Bez reklam. Bez subskrypcji.</strong> Jednorazowy zakup, a kolejne aktualizacje ARVION są wliczone.</p><a class="store-button" href="${play}" target="_blank" rel="noopener">POBIERZ W GOOGLE PLAY</a>${notePl?`<span class="store-note">${notePl}</span>`:''}`}});
const productData={
'obd':mkProduct({title:'OBD Active Exhaust Pro',icon:'assets/obd.webp',enSub:'Complete automotive tools in one Android app.',plSub:'Kompletny zestaw narzędzi samochodowych w jednej aplikacji.',en:'Control active exhaust functions, view live vehicle parameters through a compatible OBD/ELM327 connection, use diagnostics and access additional driver tools. The application combines automotive functions in one clear interface.',pl:'Steruj funkcjami aktywnego wydechu, obserwuj parametry pojazdu przez kompatybilne OBD/ELM327, korzystaj z diagnostyki i dodatkowych narzędzi dla kierowcy. Aplikacja łączy funkcje samochodowe w jednym czytelnym interfejsie.',gallery:[{src:'assets/obd.webp',alt:'OBD Active Exhaust Pro'}],play:'https://play.google.com/store/search?q=OBD%20Active%20Exhaust%20Pro&c=apps'}),
'drive-recorder':mkProduct({title:'Drive Recorder',icon:'assets/drive-recorder.webp',enSub:'Full HD driving recorder with GPS and road-focused tools.',plSub:'Rejestrator jazdy Full HD z GPS i narzędziami dla kierowcy.',en:'Turn your Android phone into a driving recorder. The application offers a dashboard-style interface for recording journeys, GPS information, loop recording, storage management and quick access to recording tools.',pl:'Zmień telefon z Androidem w rejestrator jazdy. Aplikacja oferuje interfejs w stylu samochodowego kokpitu, nagrywanie tras, informacje GPS, nagrywanie w pętli, zarządzanie pamięcią i szybki dostęp do funkcji nagrywania.',gallery:[{src:'7e9c2f92-e74d-474b-b17d-d4345413b7d7.png',alt:'Drive Recorder original screenshot'},{src:'assets/drive-recorder.webp',alt:'Drive Recorder'}],play:'https://play.google.com/store/search?q=Drive%20Recorder%20ARVION&c=apps'}),
'watch-faces':mkProduct({title:'ARVION Watch Faces',icon:'assets/watch-faces.webp',enSub:'Premium Wear OS watch faces in many visual styles.',plSub:'Tarcze premium Wear OS w wielu różnych stylach.',en:'A growing collection of watch faces for compatible Wear OS smartwatches, including classic, digital, automotive, animated and artistic designs. Browse the collection from Android and give your watch a distinctive ARVION look.',pl:'Rozwijana kolekcja tarcz dla kompatybilnych smartwatchy Wear OS, obejmująca projekty klasyczne, cyfrowe, motoryzacyjne, animowane i artystyczne. Przeglądaj kolekcję na Androidzie i nadaj zegarkowi charakterystyczny styl ARVION.',gallery:[{src:'assets/watch-faces.webp',alt:'ARVION Watch Faces'}],play:'https://play.google.com/store/search?q=ARVION%20Watch%20Faces&c=apps'}),
'checkers-royal':mkProduct({title:'Checkers Royal Game',icon:'assets/checkers.webp',enSub:'Royal checkers for Android and compatible Wear OS watches.',plSub:'Królewskie warcaby na Androida i kompatybilne zegarki Wear OS.',en:'Classic checkers in an ornate black, gold and emerald presentation. Play against AI or locally with two players and enjoy simple touch controls. A smartwatch version is also available for compatible Wear OS devices.',pl:'Klasyczne warcaby w ozdobnej czarno-złoto-szmaragdowej oprawie. Graj przeciwko AI lub lokalnie w dwie osoby i korzystaj z prostego sterowania dotykowego. Dostępna jest również wersja na kompatybilne zegarki Wear OS.',gallery:[{src:'1f7b7381-74c7-4af8-a345-961b4afd158d.png',alt:'Checkers Royal Game original promotional image'},{src:'37e1950b-eda3-4b38-ad6f-7e4a40b62abe.png',alt:'Checkers Royal Game original promotional image'}],play:'https://play.google.com/store/apps/details?id=com.aplikacjeandroid.checkersroyalgame',noteEn:'Also available in a smartwatch version.',notePl:'Dostępna również w wersji na zegarek.'}),
'royal-chess':mkProduct({title:'Royal Chess',icon:'assets/chess.webp',enSub:'Classic chess with AI and a premium royal interface.',plSub:'Klasyczne szachy z AI i królewskim interfejsem premium.',en:'Royal Chess combines traditional chess rules with a detailed gold-and-blue presentation. Play against the computer, choose an AI level, use match timers and manage the game with pause and history controls.',pl:'Royal Chess łączy tradycyjne zasady szachów ze szczegółową złoto-granatową oprawą. Graj przeciwko komputerowi, wybierz poziom AI, korzystaj z zegarów partii oraz funkcji pauzy i historii.',gallery:[{src:'1.jpeg',alt:'Royal Chess original promotional image'},{src:'3.jpeg',alt:'Royal Chess original gameplay screenshot'},{src:'assets/chess.webp',alt:'Royal Chess'}],play:'https://play.google.com/store/search?q=Royal%20Chess%20ARVION&c=apps'}),
'chicken-drop':mkProduct({title:'Chicken Drop',icon:'assets/chicken-drop.webp',enSub:'Fast arcade gameplay made for short Android sessions.',plSub:'Szybka gra zręcznościowa na krótkie rozgrywki na Androidzie.',en:'A casual arcade game focused on simple controls, quick reactions and short sessions. Start playing immediately and improve your result with each attempt.',pl:'Casualowa gra zręcznościowa oparta na prostym sterowaniu, szybkim refleksie i krótkich sesjach. Rozpocznij grę od razu i poprawiaj swój wynik z każdą próbą.',gallery:[{src:'assets/chicken-drop.webp',alt:'Chicken Drop'}],play:'https://play.google.com/store/search?q=Chicken%20Drop%20ARVION&c=apps'}),
'crystal-blocks':mkProduct({title:'Crystal Blocks',icon:'assets/crystal-blocks.webp',enSub:'A crystal-themed falling-block puzzle with levels and scores.',plSub:'Kryształowa gra logiczna ze spadającymi blokami, poziomami i wynikami.',en:'Arrange falling blocks, clear lines and build your score in a colorful crystal-themed puzzle. The game includes levels, combos, a next-piece preview and touch-friendly controls.',pl:'Układaj spadające klocki, usuwaj linie i zdobywaj coraz lepszy wynik w kolorowej kryształowej oprawie. Gra oferuje poziomy, combo, podgląd kolejnego klocka i sterowanie dotykowe.',gallery:[{src:'assets/crystal-blocks.webp',alt:'Crystal Blocks'}],play:'https://play.google.com/store/apps/details?id=com.aplikacjeandroid.crystalblocks.app'}),
'kalendarz-zmianowy':mkProduct({title:'Kalendarz Zmianowy',icon:'assets/kalendarz.webp',enSub:'A practical calendar for shift schedules and work planning.',plSub:'Praktyczny kalendarz do grafiku zmianowego i planowania pracy.',en:'Keep your shift schedule organized in one place. Use calendar navigation, work-time information, notes and history to make everyday planning easier.',pl:'Uporządkuj swój grafik zmianowy w jednym miejscu. Korzystaj z nawigacji po kalendarzu, informacji o czasie pracy, notatek i historii, aby ułatwić codzienne planowanie.',gallery:[{src:'assets/kalendarz.webp',alt:'Kalendarz Zmianowy'}],play:'https://play.google.com/store/search?q=Kalendarz%20Zmianowy%20ARVION&c=apps'}),
'live-data':mkProduct({title:'Live Data',icon:'assets/live-data.webp',enSub:'Real-time vehicle parameters through compatible OBD/ELM327.',plSub:'Parametry pojazdu na żywo przez kompatybilne OBD/ELM327.',en:'View selected ECU and vehicle parameters in real time on your Android phone. Live Data is designed around a clear automotive dashboard and a compatible OBD/ELM327 connection.',pl:'Obserwuj wybrane parametry ECU i pojazdu w czasie rzeczywistym na telefonie z Androidem. Live Data wykorzystuje czytelny samochodowy kokpit i kompatybilne połączenie OBD/ELM327.',gallery:[{src:'assets/live-data.webp',alt:'Live Data'}],play:'https://play.google.com/store/search?q=Live%20Data%20ARVION%20OBD&c=apps'}),
'media-player':mkProduct({title:'Media Player',icon:'assets/media.webp',enSub:'Local media playback with playlists and visual presentation.',plSub:'Odtwarzanie lokalnych multimediów z playlistami i wizualizacją.',en:'Play local media from a clear ARVION interface with playlists, playback controls, audio-output options and spectrum-style visualizers.',pl:'Odtwarzaj lokalne multimedia w czytelnym interfejsie ARVION z playlistami, sterowaniem odtwarzaniem, opcjami wyjścia audio i wizualizacjami typu spectrum.',gallery:[{src:'assets/media.webp',alt:'Media Player'}],play:'https://play.google.com/store/search?q=ARVION%20Media%20Player&c=apps'}),
'music-2-watch':mkProduct({title:'Music 2 Watch',icon:'assets/music-2-watch.webp',enSub:'Music features for Android phone and compatible Wear OS watch.',plSub:'Funkcje muzyczne dla telefonu z Androidem i kompatybilnego zegarka Wear OS.',en:'Extend music playback to your wrist. Music 2 Watch is designed for a phone-and-watch setup so your own music and playback controls can be conveniently available on a compatible smartwatch.',pl:'Rozszerz obsługę muzyki na nadgarstek. Music 2 Watch współpracuje z telefonem i zegarkiem, aby własna muzyka i sterowanie odtwarzaniem były wygodnie dostępne na kompatybilnym smartwatchu.',gallery:[{src:'assets/music-2-watch.webp',alt:'Music 2 Watch'}],play:'https://play.google.com/store/apps/details?id=pl.arvion.music2watch'}),
'pixel-critters':mkProduct({title:'Pixel Critters',icon:'assets/pixel-critters.webp',enSub:'A retro pixel virtual-pet experience for Android.',plSub:'Retro wirtualny pupil w pikselowym stylu na Androida.',en:'A nostalgic pixel-art creature game inspired by classic virtual pets. Care for your critter, follow its status and enjoy simple interactions designed for everyday casual play.',pl:'Nostalgiczna gra pixel-art inspirowana klasycznymi wirtualnymi pupilami. Opiekuj się swoim stworzeniem, obserwuj jego stan i korzystaj z prostych interakcji przeznaczonych do codziennej zabawy.',gallery:[{src:'assets/pixel-critters.webp',alt:'Pixel Critters'}],play:'https://play.google.com/store/apps/details?id=com.aplikacjeandroid.pixelcritters'}),
'pixel-critters-3d':mkProduct({title:'Pixel Critters 3D',icon:'assets/pixel-critters-3d.webp',enSub:'A 3D creature adventure with rooms, characters and mini-games.',plSub:'Przygoda 3D ze stworzeniami, pokojami, postaciami i mini-grami.',en:'Pixel Critters 3D expands the virtual-creature idea into a colorful 3D world. Interact with characters, explore rooms and enjoy additional activities and mini-games.',pl:'Pixel Critters 3D rozwija pomysł wirtualnego stworzenia w kolorowy świat 3D. Wchodź w interakcje z postaciami, odwiedzaj pokoje i korzystaj z dodatkowych aktywności oraz mini-gier.',gallery:[{src:'2.jpeg',alt:'Pixel Critters 3D original screenshot'},{src:'assets/pixel-critters-3d.webp',alt:'Pixel Critters 3D'}],play:'https://play.google.com/store/apps/details?id=com.pixelcritters3d.game'}),
'snake-classic':mkProduct({title:'Snake Classic',icon:'assets/snake.webp',enSub:'The timeless Snake formula in an Android edition.',plSub:'Ponadczasowy Snake w wersji przygotowanej na Androida.',en:'Guide the snake, collect targets, grow longer and try to beat your best score. Snake Classic keeps the familiar arcade rules in a simple touch-friendly form.',pl:'Steruj wężem, zbieraj cele, rośnij i próbuj pobić swój najlepszy wynik. Snake Classic zachowuje znane zasady zręcznościowe w prostej formie wygodnej na ekranie dotykowym.',gallery:[{src:'assets/snake.webp',alt:'Snake Classic'}],play:'https://play.google.com/store/apps/details?id=pl.snakeclassic.game'}),
'spy-2-watch':mkProduct({title:'Spy 2 Watch',icon:'assets/spy-2-watch.webp',enSub:'Phone-camera preview and controls for a compatible Wear OS watch.',plSub:'Podgląd kamery telefonu i sterowanie z kompatybilnego zegarka Wear OS.',en:'Connect selected phone camera functions with a compatible smartwatch. Spy 2 Watch provides a wrist-focused interface for preview, camera/session controls and access to recordings depending on the selected mode.',pl:'Połącz wybrane funkcje kamery telefonu z kompatybilnym smartwatchem. Spy 2 Watch oferuje interfejs na nadgarstku do podglądu, sterowania kamerą i sesją oraz dostępu do nagrań zależnie od wybranego trybu.',gallery:[{src:'BANER STRONA GLOWNA.png',alt:'Spy 2 Watch original banner'},{src:'ChatGPT Image 27 sie 2026, 19_21_18 (2).png',alt:'Spy 2 Watch original promotional image'},{src:'assets/spy-2-watch.webp',alt:'Spy 2 Watch'}],play:'https://play.google.com/store/search?q=Spy%202%20Watch%20ARVION&c=apps'}),
'video-2-watch':mkProduct({title:'Video 2 Watch',icon:'assets/video-2-watch.webp',enSub:'Your own video files on a compatible Wear OS smartwatch.',plSub:'Własne pliki wideo na kompatybilnym smartwatchu Wear OS.',en:'Manage selected video files on your Android phone and make them available on a compatible smartwatch. Depending on the connection mode, Video 2 Watch supports a phone-and-watch workflow for transfer, streaming and playback.',pl:'Zarządzaj wybranymi plikami wideo na telefonie z Androidem i udostępniaj je na kompatybilnym smartwatchu. Zależnie od trybu połączenia Video 2 Watch obsługuje przesyłanie, strumieniowanie i odtwarzanie w zestawie telefon plus zegarek.',gallery:[{src:'assets/video-2-watch.webp',alt:'Video 2 Watch'}],play:'https://play.google.com/store/apps/details?id=pl.arvion.video2watch'})
};
'''
p.write_text(s[:a]+CAT+s[b:],encoding='utf-8')
print('Updated 16 ARVION product pages')
